export const LOGS_UPLOAD_STARTED = "LOGS_UPLOAD_STARTED";
export const LOGS_UPLOAD_SUCCESS = "LOGS_UPLOAD_SUCCESS";
export const LOGS_UPLOAD_FAILURE = "LOGS_UPLOAD_FAILURE";
export const LOGS_PARSED_STARTED = "LOGS_PARSED_STARTED";
