export const LOGS_UPLOAD_STARTED = "LOGS_UPLOAD_STARTED";
export const LOGS_UPLOAD_SUCCESS = "LOGS_UPLOAD_SUCCESS";
export const LOGS_UPLOAD_FAILURE = "LOGS_UPLOAD_FAILURE";
export const LOGS_PARSED_STARTED = "LOGS_PARSED_STARTED";
export const LOGS_REQUEST_STARTED = "LOGS_REQUEST_STARTED";
export const LOG_REQUEST_STARTED = "LOG_REQUEST_STARTED";
